### PR TITLE
Fixed Qt6 warnings, added Qt6 auto detection

### PR DESCRIPTION
**Pull request by asafran**
Fixed Qt6 warnings
Automatic Qt selection in CMake. https://doc.qt.io/qt-6/cmake-qt5-and-qt6-compatibility.html
#21 

Tested on Fedora 37, Qt 5.15.8, Qt 6.2.2, Qt 6.4.2

### CODE REVIEW

**Comment by robertosfield** [comment]
I am away on trip right now so just doing a quick review, on my return I'll do a proper test.

My first thought on review is that we should have a convert_coord method that takes an event and implements the appropriate coord conversion for Qt5 and Qt6 rather than have three separate #idef blocks spread through the implementation.  We could pass back the coords as a std::pair, or have two methods convert_coord_x(event) and convert_coord_y(event).

I am happy to tinker with this on my return.

**Comment by asafran** [comment]
There the Qt API was changed, the code sections separated by define cannot be compiled on the old version.
I don't think this fix is necessary at all. But Qt can remove deprecated functions from recent versions of Qt6.

**Comment by robertosfield** [comment]
I am now back from my trip and starting to look at this PR.  I've merged the PR a branch for testing:

https://github.com/vsg-dev/vsgQt/tree/asafran-Qt6WarningFix

I am still trying to figure out what the best approach is.  Automatically selecting Qt5 or Qt6 seems like it could break applications - if a users application uses Qt5 and vsgQt automatically selects Qt6 then it'll break things, and visa-versa.

Is this resolvable?  

Do we actually need to build both a vsgQt5 and vsgQt6 lib?

Hiding the Qt5 vs Qt6 differences within the source code and keeping the public headers functional for both Qt5 and Qt6 seems like a good goal if we can maintain it.

**Comment by robertosfield** [comment]
I have had a bash at Qt warnings and have merged this with [vsgQt master](https://github.com/vsg-dev/vsgQt/pull/24).  I have tested with Qt6 and it's building and functioning cleanly for me.  It's similar to this PR but avoids spreading the #if Qt6 blocks out between functions by introducing a convertMousePosition(..) method that is similar to the prexisting convertMouseButtons() method, it's implemented thus:

std::pair<int32_t, int32_t> ViewerWindow::convertMousePosition(QMouseEvent* e) const
{
#if QT_VERSION_MAJOR == 6
    return {convert_coord(e->position().x()), convert_coord(e->position().y())};
#else
    return {convert_coord(e->x()), convert_coord(e->y())};
#endif
}

Use is simply:

    auto [mask, button] = convertMouseButtons(e);
    auto [x, y] = convertMousePosition(e);

I merged the template convert_coord() method() from this PR as this is cleaner than the original code.

I haven't merged the changes to CMakeLists.txt from this PR.  I don't want to make any changes in this area until we settle upon how we want to manage the whole Qt5 and Qt6 build issue.  If 3rd parties are to package vsgQt then they'll need to decide which version of Qt to support and will likely end up trying to decide which, or how to have both and then name them.  I think it better we just figure this out up front so we don't end up with different folks choosing different paths.

A discussion thread on the VSG Discussion forum is the best place to decide this.

I'll leave this PR up for the time being.

**Comment by robertosfield** [comment]
I'm closing this PR now as the warnings have been fixed.  The changes to CMakeLists.txt we'll need to separately address.  I've created a Discussion thread to discuss this topic further:

https://github.com/vsg-dev/VulkanSceneGraph/discussions/744

**Pull request closed without merging**
